### ISSUE TITLE
TODO: Multipages

### ISSUE THREAD

**Issue by merqurio** [iomedhealth/website#1]
- [x] Clean contacts scss
- [x] Add photo of Alvaro & Javi
- [x] Check the text in about
- [x] Create contact request
- [x] Deploy new version
