### ISSUE TITLE
TODO: Product

### ISSUE THREAD

**Issue by merqurio** [iomedhealth/website#2]
- [x] Define a sketch
- [x] Find a way to do the scroll effect
- [x] Add the design elements
- [ ] Create the animations
- [ ] Add the list at the bottom

**Comment by merqurio** [comment]
Scrool effect with --> [scrollmagic.io](http://scrollmagic.io)
